services:
  ### Symfony/PHP App ###
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/matches?serverVersion=16&charset=utf8"
    command: php -S 0.0.0.0:8000 -t public

  ### PostgreSQL Database ###
  database:
    image: postgres:16-alpine
    container_name: symfony_db
    environment:
      POSTGRES_DB: matches
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database_data:
